### ISSUE TITLE
games inputData function must also be defined in the game template

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-games#2]
the game currently bugs out after the first go, because the inputData function is not defined. This must be added to the template in expfactory-python

**Comment by vsoch** [comment]
done, and added button to download data to appear two seconds after game completes:

![image](https://cloud.githubusercontent.com/assets/814322/14235373/484906bc-f9b1-11e5-85a5-f505c7aad14e.png)

@boomsbloom - should the trial ids only be odd? There are the correct number (13), so I'm guessing the evens are saved for some component of the game that isn't data collection, or something like that.

**Comment by jonathanicholas** [comment]
silly double logging typo on my end: 6ce5b9b

**Comment by vsoch** [comment]
haha, np! Closing this issue.
