### ISSUE TITLE
bucket_game:  should problem_id be null in data export?

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-games#3]
![image](https://cloud.githubusercontent.com/assets/814322/14545747/825d14ae-0255-11e6-8ff7-6dd5ce2884f4.png)

Also, how in the data do I know how many tries I took to get each problem right?

**Comment by jonathanicholas** [comment]
the problems are logged each time so you can just look at repeated problems or you can look at accuracy. but the problem_id field was handling this previously (query on problem id count). That's currently factored into the postgres db we were using so what I'll do later today or tomorrow is add a problem_id for each problem in problems.js and then re-add this field to all of the games
