### ISSUE TITLE
add_it_up_lightning: data saves too early

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-games#7]
the trigger to end the experiment seems to happen about halfway through, indicated by the option to download the data in the upper left:

![early_finish](https://cloud.githubusercontent.com/assets/814322/14571202/c0a87e7c-02fc-11e6-8e68-a8c325a58459.png)

At the end of the game, clicking the button downloaded three different data files.

**Comment by vsoch** [comment]
Just tested for zen mode - for zen version it happens on the last question, but before I've answered it, and downloading the data downloads only two files.

**Comment by cbattista** [comment]
sweet sweet asynchrony

**Comment by jonathanicholas** [comment]
weird. I didn't change anything from our other stuff which triggers once an answer has been made. lemme check the phaser stuff again though..

**Comment by vsoch** [comment]
I'm going to test the rest and report here:
- is_it_equal_lightning: reports finished at 23/25 questions

**Comment by jonathanicholas** [comment]
oh i totally misread this. its not an issue with savedata but rather when finished is going from 0 --> 1.

**Comment by jonathanicholas** [comment]
so these are totally my bad -- combination of it being a few months since i wrote the bulk of this code and not adequately testing before committing. The fix was just that I was tracking with number of trials performed rather than the global trial number. Just need to implement that in each of the games and I'll close this.

**Comment by vsoch** [comment]
excellent!

**Comment by vsoch** [comment]
ok I just tested the zen version of add it up - just want to confirm that the link to start the game should appear again at the end?

**Comment by jonathanicholas** [comment]
yeah that's legacy from our old quitGame function that I left in because I thought the experiment would end before the event fired. Probably best to comment that out for now.

**Comment by jonathanicholas** [comment]
done

**Comment by vsoch** [comment]
ok, I think we are good! I'm going to push these to expfactory.github.io
