### ISSUE TITLE
change order of equal unequal buttons?

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-games#8]
This might just be me, but I associate left with negative, right with positive, and I kept wanting "equal" to be on the right, and "unequal" on the left, and screwing up rather badly because of it. Would it make sense, given how people think of numbers increasing left to right, to change the order of the buttons?

![image](https://cloud.githubusercontent.com/assets/814322/14571566/c253d742-02fe-11e6-9f9d-dd68a006d145.png)

**Comment by cbattista** [comment]
i agree with this

**Comment by cbattista** [comment]
also that's called the 'SNARC effect'

**Comment by vsoch** [comment]
S.... NARF! 

https://www.youtube.com/watch?v=1o620WWho-o#t=0m40s

**Comment by cbattista** [comment]
my feelings exactly
